WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
), SECOND_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM FIRST_GEN)
)
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID FROM SECOND_GEN)
ORDER BY ID