WITH CHILDREN AS (
    SELECT PARENT_ID, COUNT(*) AS 'COUNT'
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)
SELECT ID, IFNULL(C.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN CHILDREN C
ON E.ID = C.PARENT_ID
ORDER BY ID