WITH PLAN_30_DURATION AS (
    SELECT CAR_TYPE, DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
), RESERVED_CAR_IDS AS (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT
        (START_DATE >= '2022-12-01' OR END_DATE < '2022-11-01')
), RENTABLE_CARS AS (
    SELECT DISTINCT H.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON C.CAR_ID = H.CAR_ID
    WHERE 
        C.CAR_ID NOT IN (SELECT CAR_ID FROM RESERVED_CAR_IDS) AND 
        C.CAR_TYPE IN ('세단', 'SUV')
)
SELECT 
    R.CAR_ID, 
    R.CAR_TYPE,
    R.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) DIV 100 AS FEE
FROM RENTABLE_CARS R
JOIN PLAN_30_DURATION P
ON R.CAR_TYPE = P.CAR_TYPE
WHERE
    R.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100 >= 500000 AND
    R.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100 <  2000000
ORDER BY 
    FEE DESC,
    R.CAR_TYPE,
    R.CAR_ID DESC