WITH SIZE_RANK AS (
    SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R
    FROM ECOLI_DATA
), TOTAL AS (
    SELECT COUNT(*) AS C
    FROM ECOLI_DATA
)
SELECT 
    ID,
    CASE 
        WHEN R <= (SELECT C / 4 FROM TOTAL) THEN 'CRITICAL'
        WHEN R <= (SELECT 2 * C / 4 FROM TOTAL) THEN 'HIGH'
        WHEN R <= (SELECT 3 * C / 4 FROM TOTAL) THEN 'MEDIUM'
        ELSE 'LOW'
    END
    AS COLONY_NAME
FROM SIZE_RANK
ORDER BY ID
