WITH JOINED_AT_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)

SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM JOINED_AT_2021), 1
    ) AS PURCHASED_RATION
FROM ONLINE_SALE
-- 2021년에 가입한 사람들의 구매 데이터
WHERE USER_ID IN (SELECT USER_ID FROM JOINED_AT_2021) 
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
