SELECT CONCAT(Q, 'Q') AS QUARTER, ECOLI_COUNT
FROM (
    SELECT
        CEIL(MONTH(DIFFERENTIATION_DATE) / 3) AS Q,
        COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    GROUP BY CEIL(MONTH(DIFFERENTIATION_DATE) / 3) 
) X