SELECT CONCAT(Q.QUARTER, 'Q') AS QUARTER, ECOLI_COUNT
FROM (
    SELECT
        QUARTER(DIFFERENTIATION_DATE) AS QUARTER,
        COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    GROUP BY QUARTER(DIFFERENTIATION_DATE)
) Q
ORDER BY QUARTER