WITH RENTAL_PERIODS AS (
    SELECT 
        H.HISTORY_ID,
        H.CAR_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS PERIOD,
        C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON 
        C.CAR_TYPE = '트럭' AND
        H.CAR_ID = C.CAR_ID
), TRUCK_PLANS AS (
    SELECT 
        DURATION_TYPE AS DURATION,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)
SELECT 
    P.HISTORY_ID,
    CASE 
        WHEN PERIOD >= 90 THEN (100 - (SELECT DISCOUNT_RATE FROM TRUCK_PLANS WHERE DURATION = '90일 이상')) * PERIOD * DAILY_FEE DIV 100
        WHEN PERIOD >= 30 THEN (100 - (SELECT DISCOUNT_RATE FROM TRUCK_PLANS WHERE DURATION = '30일 이상')) * PERIOD * DAILY_FEE DIV 100
        WHEN PERIOD >=  7 THEN (100 - (SELECT DISCOUNT_RATE FROM TRUCK_PLANS WHERE DURATION = '7일 이상')) * PERIOD * DAILY_FEE DIV 100
        ELSE PERIOD * DAILY_FEE
        END AS FEE
FROM RENTAL_PERIODS P
ORDER BY FEE DESC, HISTORY_ID DESC