WITH RECURSIVE HOURS AS (
    SELECT 0 AS H
    
    UNION ALL
    
    SELECT H+1 
    FROM HOURS
    WHERE H < 23
)
SELECT H.H AS HOUR, IFNULL(SUM(O.DATETIME IS NOT NULL), 0) AS COUNT
FROM ANIMAL_OUTS O
RIGHT JOIN HOURS H
ON H.H = HOUR(O.DATETIME)
GROUP BY H.H
ORDER BY HOUR