WITH FRONTEND_CODES AS (
    SELECT CODE FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
WHERE 0 <> ANY (
    SELECT D.SKILL_CODE & CODE
    FROM FRONTEND_CODES
) 
ORDER BY ID