WITH PARENTS_OF_RARE AS (
    SELECT TREE.ITEM_ID
    FROM ITEM_INFO INFO
    JOIN ITEM_TREE TREE
    ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
    WHERE INFO.RARITY = 'RARE'
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_ID FROM PARENTS_OF_RARE)
ORDER BY ITEM_ID DESC