WITH Python_OR_C AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('PYTHON', 'C#')
)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT *
    FROM Python_OR_C PC
    WHERE D.SKILL_CODE & PC.CODE <> 0
    )
ORDER BY ID