WITH FISH_RANK AS (
    SELECT *,
        RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS R
    FROM FISH_INFO
)
SELECT 
    R.ID AS ID,
    N.FISH_NAME AS FISH_NAME,
    R.LENGTH
FROM FISH_RANK R
JOIN FISH_NAME_INFO N
ON R.FISH_TYPE = N.FISH_TYPE
WHERE R = 1
ORDER BY ID