WITH RANKS AS (
    SELECT 
        *,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS R 
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT 
    CATEGORY, 
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM RANKS
WHERE R = 1
ORDER BY MAX_PRICE DESC