WITH FE AS (
    SELECT 'FE' AS NAME, SUM(CODE) AS 'CODE' FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY = 'Front End'
), LANG AS (
    SELECT NAME, CODE FROM SKILLCODES
    WHERE NAME IN('Python', 'C#')
), TARGET_SKILLCODES AS (
    SELECT * FROM FE
    
    UNION
    
    SELECT * FROM LANG
)

SELECT 
    CASE 
        WHEN SUM(S.NAME = 'FE' OR S.NAME = 'Python') = 2 THEN 'A'
        WHEN SUM(S.NAME = 'C#') = 1 THEN 'B'
        WHEN SUM(S.NAME = 'FE') = 1 THEN 'C'
        ELSE 'N'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
JOIN TARGET_SKILLCODES S
ON D.SKILL_CODE & S.CODE <> 0
GROUP BY D.ID, D.EMAIL
HAVING GRADE IN ('A', 'B', 'C')
ORDER BY GRADE, ID